spring:
  application:
    name: gateway

server:
  port: 9999

zuul:
  routes:
    transactions:
      path: /transactions/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: https://jovs5zmau3.execute-api.eu-west-1.amazonaws.com/prod/transactions

service:
  transactions:
    username: code-challenge
    password: payvisioner